### ISSUE TITLE
Merging Stack Decoder - part 2 - OP code

### ISSUE THREAD

**Issue by ghost** [aburkhalter512/css422#4]
Stand-alone version can handle most of the OP code except the MOVEA.

**Comment by ghost** [comment]
I'm seeing some problem with stack output again.
My previous code based on documentation is not functioning with current output.
With SUBA Test instruction, I'm receiving  0300 0488 A000 for my EA decoder.
I can clearly see that a000 is data, but other than that doesn't make sense to me.

**Comment by Turray** [comment]
I've done a simple test where I have isolated your system from the Opcode and EA decoders. The result from PROCESSS_OC of SUBA.W $FFFFA000, A4 is 0AA1 03 04 A000 01 60, which is entirely correct.
