### ISSUE TITLE
Opcode Decoder: Potential Immediate Addressing Mode Bug

### ISSUE THREAD

**Issue by Turray** [aburkhalter512/css422#44]
For instructions that have immediate addressing modes (#<data>), I have to make sure that byte data is passed to GET_EA as a word. For example, the decimal data 12 should be stored as $000D. I haven't noticed any bugs yet, but I'm making an issue so that I remember to verify all immediate addressing modes when testing.

**Comment by ghost** [comment]
There's issue with OPCODE that uses displacement.
Especially, branching instructions are not decoded properly when they use displacement in OPCODE.

**Comment by Turray** [comment]
How so?

**Comment by ghost** [comment]
It is interpreted as a data of other instruction. Try $600c to see this
issue.
