### ISSUE TITLE
String Stack Decoder Crash

### ISSUE THREAD

**Issue by Turray** [aburkhalter512/css422#45]
The String Stack Decoder (SSD), or I/O system, crashes the program after decoding an instruction. Pressing Run, or F9, as soon as the execution begins, the console displays the decoded instruction, but upon closing the execution window, the program immediately crashes. I _think_ the problem is that the stack is being pushed downward past $00FFFFFF to $00000002. Would this be a stack underflow?

Note: I have made sure that the problem is isolated to the SSD, and not related to the Opcode or EA Decoders.

**Comment by ghost** [comment]
Case solved

**Comment by Turray** [comment]
The bug is back. I believe the bug was reintroduced in 5da568ecf6ad291557035a274bba2a9749acc98e.

**Comment by ghost** [comment]
Bug is fixed, again.
